name: CI / Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Build, test and generate docs
        run: ./gradlew test fatJar dokkaHtml

      - name: Zip docs
        run: zip -r build/libs/docs.zip build/dokka/html

      - name: Create GitHub Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: "Build #${{ github.run_number }}"
          prerelease: true
          files: |
            build/libs/*-all.jar
            build/libs/docs.zip
